# Colors (Challenger Deep)
colors:
  # Default colors
  primary:
    background: '0x1e1c31'
    foreground: '0xcbe1e7'
  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xff271d'
    cursor: '0xfbfcfc'
  # Normal colors
  normal:
    black:   '0x141228'
    red:     '0xff5458'
    green:   '0x62d196'
    yellow:  '0xffb378'
    blue:    '0x65b2ff'
    magenta: '0x906cff'
    cyan:    '0x63f2f1'
    white:   '0xa6b3cc'
  # Bright colors
  bright:
    black:   '0x565575'
    red:     '0xff8080'
    green:   '0x95ffa4'
    yellow:  '0xffe9aa'
    blue:    '0x91ddff'
    magenta: '0xc991e1'
    cyan:    '0xaaffe4'
    white:   '0xcbe3e7'


font:
  normal:
    family: JetBrains Mono
  size: 13.5

scrolling:
  history: 10000
  multiplier: 3

shell:
  program: /bin/zsh
  args: 
    - -c
    - "/opt/homebrew/bin/tmux a -t 0 || /opt/homebrew/bin/tmux"

key_bindings:
  # delete one word to the left
  - key: Back
    mods: Control
    chars: "\x15"
  # tmux - detach
  - key: D
    mods: Command
    chars: "\x02d"
  # tmux in tmux - detach
  - key: D
    mods: Command|Shift
    chars: "\x02\x02d"
  # tmux - kill pane
  - key: W
    mods: Command
    chars: "\x02x"
  # tmux in tmux - kill pane
  - key: W
    mods: Command|Shift
    chars: "\x02\x02x"
  # tmux - select pane to the left
  - key: Left
    mods: Command
    chars: "\x02h"
  # tmux in tmux - select pane to the left
  - key: Left
    mods: Command|Shift
    chars: "\x02\x02h"
  # tmux - select pane to the right
  - key: Right
    mods: Command
    chars: "\x02l"
  # tmux in tmux - select pane to the right
  - key: Right
    mods: Command|Shift
    chars: "\x02\x02l"
  # tmux - select pane to the up
  - key: Up
    mods: Command
    chars: "\x02k"
  # tmux in tmux - select pane to the up
  - key: Up
    mods: Command|Shift
    chars: "\x02\x02k"
  # tmux - select pane to the down
  - key: Down
    mods: Command
    chars: "\x02j"
  # tmux in tmux - select pane to the down
  - key: Down
    mods: Command|Shift
    chars: "\x02\x02j"
  # tmux - new pane to the left
  - key: Left
    mods: Command|Alt
    chars: "\x02%\x02"
  # tmux in tmux - new pane to the left
  - key: Left
    mods: Command|Alt|Shift
    chars: "\x02\x02%"
  # tmux - new pane to the right
  - key: Right
    mods: Command|Alt
    chars: "\x02%"
  # tmux in tmux - new pane to the right
  - key: Right
    mods: Command|Alt|Shift
    chars: "\x02\x02%"
  # tmux - new pane to the up
  - key: Up
    mods: Command|Alt
    chars: "\x02\""
  # tmux in tmux - new pane to the up
  - key: Up
    mods: Command|Alt|Shift
    chars: "\x02\x02\""
  # tmux - new pane to the down
  - key: Down
    mods: Command|Alt
    chars: "\x02\""
  # tmux in tmux - new pane to the down
  - key: Down
    mods: Command|Alt|Shift
    chars: "\x02\x02\""
  # tmux - new window
  - key: T
    mods: Command
    chars: "\x02c"
  # tmux in tmux - new window
  - key: T
    mods: Command|Shift
    chars: "\x02\x02c"
  # tmux - list sessions, windows and panes
  - key: E
    mods: Command
    chars: "\x02s"
  # tmux in tmux - list sessions, windows and panes
  - key: E
    mods: Command|Shift
    chars: "\x02\x02s"
  # tmux - reload current pane
  - key: Backslash
    mods: Command
    chars: "\x02y"
  # tmux in tmux - reload current pane
  - key: Backslash
    mods: Command|Shift
    chars: "\x02\x02y"
  # tmux - select previous pane (±§)
  - key: 10
    mods: Control
    chars: "\x02;"
  # tmux in tmux - select previous pane (±§)
  - key: 10
    mods: Control|Shift
    chars: "\x02\x02;"
  # tmux - zoom current pane
  - key: Return
    mods: Command
    chars: "\x02z"
  # tmux in tmux - zoom current pane
  - key: Return
    mods: Command|Shift
    chars: "\x02\x02z"
  # tmux - select previous window
  - key: Tab
    mods: Control
    chars: "\x02\t"
  # tmux in tmux - select previous window
  - key: Tab
    mods: Control|Shift
    chars: "\x02\x02\t"
  # tmux - select window to the left
  - key: LBracket
    mods: Command
    chars: "\x02p"
  # tmux in tmux - select window to the left
  - key: LBracket
    mods: Command|Shift
    chars: "\x02\x02p"
  # tmux - select window to the right
  - key: RBracket
    mods: Command
    chars: "\x02n"
  # tmux in tmux - select window to the left
  - key: RBracket
    mods: Command|Shift
    chars: "\x02\x02n"
  # tmux - select window 0
  - key: Key0
    mods: Command
    chars: "\x020"
  # tmux in tmux - select window 0
  - key: Key0
    mods: Command|Shift
    chars: "\x02\x020"
  # tmux - select window 1
  - key: Key1
    mods: Command
    chars: "\x021"
  # tmux in tmux - select window 1
  - key: Key1
    mods: Command|Shift
    chars: "\x02\x021"
  # tmux - select window 2
  - key: Key2
    mods: Command
    chars: "\x022"
  # tmux in tmux - select window 2
  - key: Key2
    mods: Command|Shift
    chars: "\x02\x022"
  # tmux - select window 3
  - key: Key3
    mods: Command
    chars: "\x023"
  # tmux in tmux - select window 3
  - key: Key3
    mods: Command|Shift
    chars: "\x02\x023"
  # tmux - select window 4
  - key: Key4
    mods: Command
    chars: "\x024"
  # tmux in tmux - select window 4
  - key: Key4
    mods: Command|Shift
    chars: "\x02\x024"
  # tmux - select window 5
  - key: Key5
    mods: Command
    chars: "\x025"
  # tmux in tmux - select window 5
  - key: Key5
    mods: Command|Shift
    chars: "\x02\x025"
  # tmux - select window 6
  - key: Key6
    mods: Command
    chars: "\x026"
  # tmux in tmux - select window 6
  - key: Key6
    mods: Command|Shift
    chars: "\x02\x026"
  # tmux - select window 7
  - key: Key7
    mods: Command
    chars: "\x027"
  # tmux in tmux - select window 7
  - key: Key7
    mods: Command|Shift
    chars: "\x02\x027"
  # tmux - select window 8
  - key: Key8
    mods: Command
    chars: "\x028"
  # tmux in tmux - select window 8
  - key: Key8
    mods: Command|Shift
    chars: "\x02\x028"
  # tmux - select window 9
  - key: Key9
    mods: Command
    chars: "\x029"
  # tmux in tmux - select window 9
  - key: Key9
    mods: Command|Shift
    chars: "\x02\x029"
  # tmux - resize pane left
  - key: Left
    mods: Command|Control
    chars: "\x02H"
  # tmux in tmux - resize pane left
  - key: Left
    mods: Command|Control|Shift
    chars: "\x02\x02H"
  # tmux - resize pane right
  - key: Right
    mods: Command|Control
    chars: "\x02L"
  # tmux in tmux - resize pane right
  - key: Right
    mods: Command|Control|Shift
    chars: "\x02\x02L"
  # tmux - resize pane up
  - key: Up
    mods: Command|Control
    chars: "\x02K"
  # tmux in tmux - resize pane up
  - key: Up
    mods: Command|Control|Shift
    chars: "\x02\x02K"
  # tmux - resize pane down
  - key: Down
    mods: Command|Control
    chars: "\x02J"
  # tmux in tmux - resize pane down
  - key: Down
    mods: Command|Control|Shift
    chars: "\x02\x02J"
  # page scrolling
  - key: PageUp
    mods: Shift
    action: ScrollPageUp
    mode: ~Alt
  - key: PageDown
    mods: Shift
    action: ScrollPageDown
    mode: ~Alt
  - key: Home
    mods: Shift
    action: ScrollToTop
    mode: ~Alt
  - key: End
    mods: Shift
    action: ScrollToBottom
    mode: ~Alt
  # new alacritty window
  - key: "N"
    mods: Command
    action: SpawnNewInstance
