alias fdns='sudo killall -HUP mDNSResponder'
alias cl='clear'
alias sl='ls'
alias wc='tokei'
alias grep='rg'
alias find='fd'
alias x86='arch -x86_64 zsh'
alias lsusb='system_profiler SPUSBDataType'
alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
